<#
  WowAltBoard - tools/build-release.ps1

  Packs a distributable zip for a GitHub Release.

  There is deliberately no .msi / setup.exe. Nothing needs installing: the exe is
  a plain .NET Framework 4 WinExe, and PowerShell 5.1 plus .NET Framework 4.8 are
  already part of Windows 10/11 (verified on the dev machine: PS 5.1.26100,
  .NET 4.8.09221). An installer would only add Start Menu / Add-Remove entries
  while making antivirus more suspicious and breaking the "copy the folder
  anywhere" property that is the whole point of the tool. The launcher's tray
  menu has 创建桌面快捷方式 for anyone who wants an icon.

  Excluded from the zip: data/ (personal -- character names, realms, gold,
  account folder names, absolute paths, MySlot strings) and the .git directory.
#>

[CmdletBinding()]
param(
    [switch]$SkipBuild
)

$ErrorActionPreference = 'Stop'

$ToolsDir = $PSScriptRoot
if (-not $ToolsDir) { $ToolsDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
$BaseDir = Split-Path -Parent $ToolsDir

# Version comes from scan.ps1, so there is one place to bump.
$scanText = [System.IO.File]::ReadAllText((Join-Path $ToolsDir 'scan.ps1'))
$m = [regex]::Match($scanText, "\`$TOOL_VERSION\s*=\s*'([^']+)'")
if (-not $m.Success) { throw 'could not read $TOOL_VERSION from tools\scan.ps1' }
$version = $m.Groups[1].Value

Write-Host ''
Write-Host "Packing WowAltBoard v$version"
Write-Host ('-' * 62)

if (-not $SkipBuild) {
    # Dot-source rather than checking $LASTEXITCODE: a .ps1 that simply returns
    # leaves $LASTEXITCODE at whatever it was, so it is not a build signal. The
    # build script throws on real failures, which propagates here.
    & (Join-Path $ToolsDir 'build-launcher.ps1')
}

$exe = Get-ChildItem -LiteralPath $BaseDir -Filter '*.exe' -File -ErrorAction SilentlyContinue |
       Select-Object -First 1
if (-not $exe) { throw 'no launcher exe found; run tools\build-launcher.ps1 first' }

$stage = Join-Path $env:TEMP ("WowAltBoard-" + [guid]::NewGuid().ToString('N').Substring(0, 8))
$pkgDir = Join-Path $stage 'WowAltBoard'
New-Item -ItemType Directory -Path $pkgDir -Force | Out-Null

$include = @(
    'index.html', 'tests.html', 'README.md', 'LICENSE',
    '启动.bat', $exe.Name
)
foreach ($f in $include) {
    $src = Join-Path $BaseDir $f
    if (Test-Path -LiteralPath $src) { Copy-Item -LiteralPath $src -Destination $pkgDir }
    else { Write-Host "  ! missing, skipped: $f" -ForegroundColor Yellow }
}

foreach ($d in @('app', 'tools')) {
    Copy-Item -LiteralPath (Join-Path $BaseDir $d) -Destination $pkgDir -Recurse
}

# app/ and tools/ are copied wholesale, so anything dropped in them ships. These
# are the files that should not: build artifacts, caches, and the test harness.
# app/icons/ IS meant to ship -- it is what makes gear icons work offline.
$dropFromPkg = @(
    'tools\launcher.ico',        # generated by build-launcher.ps1
    'tools\.icon-cache.json',    # 57 KB of wowhead query results, dev-only
    'tools\.talent-names.json',  # 271 KB of DB2 zhCN join results, dev-only
    'tools\.talent-icon-fix.json', # bad-icon-name -> real-name table, build-time only
    'tools\.maxroll-spell-ids.json', # which spell IDs fetch-maxroll.js needs looked up; a byproduct
    'tools\.wcl-auth.json',      # the user's Warcraft Logs API credentials -- MUST NOT ship

    'tools\check-lazyload.js',   # walks the panel's lazy-load chain in a clean env; needs dom-stub.js
    'tools\check-scan-bagsync.js', # builds 0/1/2-account fake WoW trees; scanner regression test
    'tools\check-scan-backups.js', # same, for the Myslot/edit-mode backup collection path
    'tools\check-anchors.js',    # static anchor check for the mutate-* suites -- which are
                                 # themselves dropped below, so this would find nothing
    'tools\dom-stub.js',         # test harness
    'tools\run-tests.js',        # test harness
    'tools\mutate-a11y.js',     # mutation suite for the a11y assertions; needs run-tests.js
    'tools\mutate-names.js',    # mutation suite for the zhCN name assertions; needs run-tests.js
    'tools\mutate-decode.js',   # mutation suite for the talent-decode assertions
    'tools\mutate-lock.js',     # the mutex those mutation suites share
    'tools\mutate-pkg.js',     # mutation suite for the packaging guard itself; needs run-tests.js
    'tools\mutate-icons.js',   # mutation suite for the talent-icon assertions
    'tools\mutate-loadout.js', # mutation suite for the talent import-string assertions
    'tools\mutate-rio.js',     # mutation suite for the raider.io data assertions
    'tools\mutate-mrtalents.js', # mutation suite for the maxroll talent-build assertions
    'tools\mutate-ilvlgap.js', # mutation suite for the ilvl / gear-gap / dropped-view assertions
    'tools\mutate-pool.js'     # mutation suite for the fetch-rio pool() regression test
)
foreach ($f in $dropFromPkg) {
    Remove-Item -LiteralPath (Join-Path $pkgDir $f) -Force -ErrorAction SilentlyContinue
}

# Directories need -Recurse; Remove-Item -Force alone will not delete a folder.
# .talent-raw/ is 14 MB of upstream downloads (raidbots talents.json + two DB2
# CSV dumps). It is gitignored, but this copies from DISK, not from git -- so
# without this line it would ship. Keep dirs and files in separate lists.
$dropDirsFromPkg = @(
    'tools\.talent-raw',        # 14 MB upstream cache for fetch-talent-tree.js
    'tools\.db2-names',         # 15 KB DB2 CSV cache for fetch-class-names.js
    'tools\.rio-raw',           # 1.9 MB raider.io cache for fetch-talent-truth.js
    'tools\.maxroll-raw',       # 50 MB of maxroll guide HTML for fetch-maxroll.js -- 81 pages, measured
    'tools\.wcl-raw'            # Warcraft Logs raw responses + OAuth token for fetch-wcl.js
)
# NOTE: keep '(' and ')' out of the comments in these two lists. run-tests.js
# finds each list with a non-greedy /@\(([\s\S]*?)\)/ -- a ')' inside a comment
# ends the capture early and everything after it silently stops being checked.
# That is how '.wcl-raw' slipped past the guard once: it sat right after a comment
# reading '(81 pages, measured)'.
foreach ($d in $dropDirsFromPkg) {
    Remove-Item -LiteralPath (Join-Path $pkgDir $d) -Recurse -Force -ErrorAction SilentlyContinue
}

# An empty data/ so the first run has somewhere to write, and a note explaining
# that the folder is regenerated.
$dataDir = Join-Path $pkgDir 'data'
New-Item -ItemType Directory -Path $dataDir -Force | Out-Null
[System.IO.File]::WriteAllText(
    (Join-Path $dataDir '说明.txt'),
    "这个文件夹由启动器自动生成，可以随时整个删掉重扫。`r`n里面是你的角色数据，不要上传到公开仓库。`r`n",
    [System.Text.UTF8Encoding]::new($true))

$zip = Join-Path $BaseDir ("WowAltBoard-v$version.zip")
if (Test-Path -LiteralPath $zip) { Remove-Item -LiteralPath $zip -Force }

Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory(
    $stage, $zip,
    [System.IO.Compression.CompressionLevel]::Optimal,
    $false)

Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue

$kb = [math]::Round((Get-Item -LiteralPath $zip).Length / 1KB, 1)
Write-Host "  $zip  ($kb KB)"
Write-Host ''
Write-Host 'Done. Attach this zip to the GitHub Release.' -ForegroundColor Green
